#!/usr/bin/env bash
# Regenerates assets/data/repos.js from the GitHub API.
# Usage: GITHUB_TOKEN=... ./scripts/update-repos.sh   (token optional, avoids rate limits)
set -euo pipefail
USER_NAME="${GH_USER:-HamzaHassanain}"
OUT="$(dirname "$0")/../assets/data/repos.js"
AUTH=()
[ -n "${GITHUB_TOKEN:-}" ] && AUTH=(-H "Authorization: Bearer $GITHUB_TOKEN")

curl -fsSL "${AUTH[@]}" -H "Accept: application/vnd.github+json" \
  "https://api.github.com/users/$USER_NAME/repos?per_page=100&type=owner&sort=pushed" \
| jq --arg user "$USER_NAME" '[.[]
    | select(.name != $user and .name != ($user + ".github.io") and (.private | not))
    | {name, url: .html_url, description, language, stars: .stargazers_count,
       forks: .forks_count, fork, homepage: (.homepage // ""), topics, pushed: .pushed_at[0:10],
       created: .created_at[0:10], archived}]' > "$OUT.tmp"

{
  echo "// Auto-generated by scripts/update-repos.sh on $(date -u +%Y-%m-%d). Do not edit by hand."
  printf 'window.REPOS = '
  cat "$OUT.tmp"
  echo ';'
} > "$OUT"
rm "$OUT.tmp"
echo "Wrote $OUT"
